// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: array_test.sql

package models

import (
	"context"

	"github.com/lib/pq"
)

const getAllColumns = `-- name: GetAllColumns :many
SELECT id, uuid, created_at, modified_at, varchar_array_field, text_array_field, int_array_field, float_array_field, bool_array_field
FROM array_test
`

func (q *Queries) GetAllColumns(ctx context.Context) ([]ArrayTestBlock, error) {
	rows, err := q.db.QueryContext(ctx, getAllColumns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ArrayTestBlock
	for rows.Next() {
		var i ArrayTestBlock
		if err := rows.Scan(
			&i.ID,
			&i.UUID,
			&i.CreatedAt,
			&i.ModifiedAt,
			pq.Array(&i.VarcharArrayField),
			pq.Array(&i.TextArrayField),
			pq.Array(&i.IntArrayField),
			pq.Array(&i.FloatArrayField),
			pq.Array(&i.BoolArrayField),
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
